language: node_js
install: npm install
script: npm run build:www
deploy:
  provider: heroku
  api_key:
    secure: PKaG50gDaoPa4bE98U0FujF0Tpggd4WMOgvv9l3tIoSu7SPE3p1su2Ff/AgdPekWxhlhgCZNwzNvHSmXshunFnAipLdBpbmocqAGhTTzsD3uKtZ86qmodWCA6WxJtgeNYwcPtx6clksgdSOQdolCzlVXyg0yFFp7iqgE6nl8QFPYL6GnrCf0dwICPYR1fCaaeVRF8/CwWDh2tEaG/DFQxnYhG2Su9+JuyuTdmzOOug+nkRcQqw9qHmJLY7OUd70ut9w31cOK+vA0VMbFh+4lG3RDBj5+v6V8deQ/+NALh76CVlCJmOKPBPuA9p2lKWS38pXNSA14lLfzN62ru7+jznXAMnBjSC6k1QFevinUPi62kpqxZCSmoP2o+Ua+KbMRbWh2hg2LIQQAg+NI/TAAxG4Asu60FGtcVFU4gLqL4J84k7ekiqeckzDAeqASRn5fhga8QH6Q2b9O6gfJyc73C5o1SjZzHRVA1YgeLSB7wfc0y8NZzHbrUT+cwImTgY+tqWnz0rKPzGL4wbFwbAzkbNcmXy8NU9sSvidQgkEBO32Qh36la/ZbIe3tzN16ZcV1dx3skLri4mo1R8c8S1RPLIVROmd3czUnMb29OB0Gox3MCJ0fhuqab5E35JuqBUdFZF+mgbkXGHRKIZwaGX2AhbJjzERuJdK8WXChC7DMAZA=
  app: sync-master
